# suppress inspection "SpringBootApplicationProperties" for whole file
server:
  port: 8880
  ssl:
    enabled: true # Resolvable hostname is required on production, use SSL by IP only in development
    strictMode: false
    key-store: classpath:keystore.jks
    key-store-password: odysseus
    key-alias: arachne
    key-password: odysseus
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
logging:
  level:
    root: INFO
    org.springframework.web.servlet.PageNotFound: ERROR
#  com.odysseusinc.arachne.datanode.service.AchillesService: DEBUG
flyway:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  out-of-order: true
api:
  loginEnteryPoint: /api/v1/auth/login
  logoutEntryPoint: /api/v1/auth/logout
  registerEntryPoint: /api/v1/auth/register

arachne:
  token:
    header: Arachne-Auth-Token

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
      connection:
        CharSet: utf8
        characterEncoding: utf8
        useUnicode: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/datanode
    username: ohdsi
    password: ENC(0Lpfvg9UPAyaaZpSIqwaDg==)
    driver-class-name: org.postgresql.Driver
    connection-test-query: select 1
    max-active: 400
  mail:
    host: smtp.gmail.com
    port: 587
    username: odysseusinc.notifier
    password:
    properties:
      mail:
#        debug=true
        smtp:
          auth: true
#          socks.host=
#          socks.port=
          starttls:
            enable: true
            required: true
  http:
    multipart:

      max-file-size 1024MB
      max-request-size: 1024MB
  mvc:
    view:
      prefix: /
      suffix: .html
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  activemq:
    packages:
      trust-all: true
build:
  number: @build.number@
  id: @build.id@
project:
  version: @project.version@
#ms
files:
  store:
    path: /var/arachne/files
datanode:
  checkDataSourceTimeout: 45000
  app:
    errorsTokenEnabled: false
  runMode: NETWORK
  jwt:
    header: Arachne-Auth-Token
    secret: 129DF19C8A91AFD8375A2826A33539K01ACQ778QOJFAA9MGWLWH73PLXVFVHBR7860MTIE2O8EEVF9KCO77P6A7NUNX4XHAGCRFSBWG879XPDOIN6C2LFCKJI002OIABS4D6Q9VMJJIX8UCE48EF
    expiration: 900
  arachneCentral:
    admin.email:
    host: https://community.arachnenetwork.com
    port: 443
    authHeader: Arachne-Auth-Token
    nodeAuthHeader: Arachne-System-Token
  httpClient:
    connectTimeout: 60
    writeTimeout: 60
    readTimeout: 60
  baseURL: https://localhost
  port: 8880
swagger:
  enable: false
proxy:
  enabled: false
  enabledForEngine: false
  host:
  port:
  auth:
    enabled: false
    username:
    password:
executionEngine:
  protocol: https
  port: 8888
  analysisUri: /api/v1/analyze
  token:
docker:
  host: tcp://localhost:2375
  tls-verify: false
  registry:
    host: hub.arachnenetwork.com
    username: user
    password:
achilles:
  image-name: hub.arachnenetwork.com/achilles:20190507
  network-mode: arachnenetwork
  auth-config:
    registry-address: hub.arachnenetwork.com
    username: user
    password:
  retry:
    max-attempts: 5
    backoff:
      max-interval: 50000
  scheduler:
    enabled: false
    cron: 0 0 12 1/5 * ?
atlas:
  host: http://localhost
  port: 8088
  urlContext: WebAPI
  auth:
    schema: NONE
    username:
    password:
  scheduler:
    checkInterval: 60000
entities:
  scheduler:
    checkListRequestsInterval: 10000
    checkRequestInterval: 10000
central:
  scheduler:
    checkingInterval: 60000

jasypt:
  encryptor:
    password:
    database:
      algorithm: PBEWITHMD5ANDDES
migration:
  retry:
    timeout: 10000
cohorts:
  result:
    countEnabled: true
    summaryEnabled: false
    defaultTargetTable: cohort
tmp:
  location-on-host:
  holder:
    cron: 0 * * ? * *
analysis:
  file.maxsize: 1048576
  scheduler:
    resendFailuresInterval: 600000
    invalidateExecutingInterval: 86400000
    invalidateMaxDaysExecutingInterval: 3
submission:
  result:
    files:
      exclusions:
security:
  authentication:
    mode: STANDARD
authenticator:
  user:
    registrationStrategy: CREATE_IF_FIRST
  methods:
    rest-central:
      service: org.ohdsi.authenticator.service.rest.RestAuthService
      config:
        bodyFormat: JSON
        params:
          username: username
          password: password
        loginSuccessCriteria:
          status: OK
          bodyProperty: '$[?(@.errorCode == 0)]'
        token:
          source: BODY
          key: $.result.token
          targetHeader: Arachne-Auth-Token
          targetFormat: '%s'
          copyExpirationDate: true
        fieldsToExtract:
          id: result.id
          email: result.email
          username: result.username
          firstName: result.firstname
          middleName: result.middlename
          lastName: result.lastname
        proxy:
          enabled: ${proxy.enabled}
          host: ${proxy.enabledForEngine}
          port: ${proxy.host}
          authEnabled: ${proxy.auth.enabled}
          username: ${proxy.auth.username}
          password: ${proxy.auth.password}


