spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datanode
datanode:
  arachneCentral:
    host: https://localhost
    port: 8080
  jwt:
    expiration: 604800
swagger:
  enable: true
executionEngine:
  host: localhost
docker:
  host: unix:///var/run/docker.sock
atlas:
  auth:
    schema: DATABASE
    username: admin@odysseusinc.com
    password: ENC(ScVtM/zv348iHQ3b+zZHytAiOcU+DbY2)
  scheduler:
      checkInterval: 10000
entities:
  scheduler:
    checkListRequestsInterval: 1000
    checkRequestInterval: 1000
cohorts:
  result:
    countEnabled: true
    summaryEnabled: true
analysis:
  scheduler:
    resendFailuresInterval: 60000
    invalidateExecutingInterval: 120000
central:
  scheduler:
    checkingInterval: 20000



authenticator:
  methods:
    rest-central:
      config:
        url: https://localhost:8080/api/v1/auth/login
        infoUrl: https://localhost:8080/api/v1/auth/me
security.method: rest-central
security.jwt.token.secretKey: ${datanode.jwt.secret}
security.jwt.token.validityInSeconds: ${datanode.jwt.expiration}
