server:
  ssl:
    enabled: false
datanode:
  arachneCentral:
    host: https://testcommunity.arachnenetwork.com
  baseURL: http://odysseusovh03.odysseusinc.com
swagger:
  enable: true
atlas:
  host: https://testatlas.arachnenetwork.com
  port: 443
  auth:
    schema: DATABASE
    username: admin@odysseusinc.com
    password: ENC(ScVtM/zv348iHQ3b+zZHytAiOcU+DbY2)
proxy:
  auth:
    username: user
    password: Password1234
executionEngine:
  host: odysseusovh02.odysseusinc.com
analysis:
  scheduler:
    invalidateExecutingInterval: 3600000
authenticator:
  methods:
    rest-central:
      config:
        url: https://testcommunity.arachnenetwork.com:8070/api/v1/auth/login
        infoUrl: https://testcommunity.arachnenetwork.com:8070/api/v1/auth/me
