server:
  ssl:
    enabled: false
datanode:
  arachneCentral:
    host: https://testcommunity.arachnenetwork.com
swagger:
  enable: true
atlas:
  host: https://testatlas.arachnenetwork.com
  port: 443
  auth:
    schema: DATABASE
    username: admin@odysseusinc.com
    password: ENC(ScVtM/zv348iHQ3b+zZHytAiOcU+DbY2)
proxy:
  auth:
    username: user
    password: Password1234
