workDir <- getwd()
dbms <- Sys.getenv("DBMS_TYPE")
connStr <- Sys.getenv("CONNECTION_STRING")
user <- Sys.getenv("DBMS_USERNAME")
pw <- Sys.getenv("DBMS_PASSWORD")
cdmDatabaseSchema <- Sys.getenv("DBMS_SCHEMA")
cohortsDatabaseSchema <-cdmDatabaseSchema
cohorts <- list({{{cohortDefinitions}}})
source("run_ir_analysis.r")
run_ir_analysis(workDir, {{analysisId}}, file.path(workDir, "analysisDescription.json"), cohorts, dbms, connStr, user, pw, cdmDatabaseSchema, cohortsDatabaseSchema, cohortTable = "cohort", outcomeTable = "cohort")
