ALTER TABLE datanode ADD COLUMN IF NOT EXISTS central_id BIGINT;
ALTER TABLE datanode ALTER COLUMN sid DROP NOT NULL;
ALTER TABLE datasource ADD COLUMN IF NOT EXISTS central_id BIGINT;
ALTER TABLE datasource ALTER COLUMN sid DROP NOT NULL;